# Use a base image that matches your production environment
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY . .

# Use Gunicorn to serve the application. Adjust the number of workers as necessary.
# The "backend_app:app" syntax specifies the module (backend_app) and application variable (app) to serve with Gunicorn.
CMD ["gunicorn", "--bind", "0.0.0.0:12345", "--workers", "3", "backend_app:app"]
