# Use the Nginx stable alpine image as a base
FROM nginx:stable-alpine

# Remove the default Nginx configuration files
RUN rm /etc/nginx/conf.d/default.conf

# Since you're directly using the modified nginx.conf without needing substitution,
# copy it directly instead of using a template
COPY nginx.conf /etc/nginx/nginx.conf
COPY static.html /usr/share/nginx/html/

# Make sure the Nginx user owns the static content directory
RUN chown -R nginx:nginx /usr/share/nginx/html

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
